### PR TITLE
Create changeSecretText.groovy

### PR DESCRIPTION
**Pull request by schulzh**
A script based on https://github.com/jenkinsci/jenkins-scripts/blob/master/scriptler/changeCredentialPassword.groovy for changing the value of a secret text

### CODE REVIEW

**Comment by schulzh** [comment]
@thomasleveil Would you rather like to have your name as author in or not?

**Comment by thomasleveil** [comment]
I prefer not, as I will not be maintaining it

**Comment by samrocketman** [comment]
This seems to search for a credentials ID.  Credentials IDs tend to be unique for a given scope.  How do you use this script in a way that you couldn't just manually save a single credentials ID?  `changeCredentialPassword.groovy` is operating based on the username (which need not be unique across credentials).  I'm not against merging this, just curious.

**Comment by schulzh** [comment]
@samrocketman Thanks for your feedback, I've implemented specifying the scope optionally.

**Comment by imod** [comment]
closing in favor of https://github.com/jenkinsci/jenkins-scripts/commit/2ff8139cf17707090f4cf52592a3416876a1af3e

**Pull request closed without merging**
