### PR TITLE
Add AnsiColor (plugin) to all jobs

### PR DESCRIPTION
**Pull request by Evildethow**
@reviewbybees

### CODE REVIEW

**Comment by Dohbedoh** [comment]
:bee:

**Comment by kuisathaverat** [comment]
🐝

**Comment by oleg-nenashev** [comment]
I'm aware that there is no applicability check, but seems it's specific to Build wrappers

**Comment by Evildethow** [comment]
@oleg-nenashev 

> I'm aware that there is no applicability check, but seems it's specific to Build wrappers

Is this an issue? Im not familiar with any requirements imposed here.

**Pull request merged**
