### PR TITLE
Add the Slack Notification (for v2.1) on all your jobs

### PR DESCRIPTION
**Pull request by aheritier**

### CODE REVIEW

**Comment by aheritier** [comment]
please @reviewbybees

**Comment by samrocketman** [comment]
Why doesn't this have any params?  Is it defaulting to the global configuration?  Also, the slack plugin has some flaws in how it references local job configuration vs falling back to global configuration.

Regarding the messed up plugin configurations see:

* https://github.com/jenkinsci/slack-plugin/issues/130
* https://github.com/jenkinsci/slack-plugin/issues/159

**Comment by imod** [comment]
@aheritier is this still relevant?

**Comment by aheritier** [comment]
No let's close. It's too old I'm not sure about what I did

**Pull request closed without merging**
