### PR TITLE
added script to disable all jobs

### PR DESCRIPTION
**Pull request by mrdfuse**

### CODE REVIEW

**Comment by imod** [comment]
@mrdfuse why did you merge this PR? this script ins incomplete - its missing the metadata as described in the README

**Comment by mrdfuse** [comment]
why? that's a long time ago :) obviously I missed that
can't push to github from work though so can't fix it atm

**Comment by imod** [comment]
I just realized the commit date, sorry for bothering - I fixed all the issues I found in the different scripts

**Comment by mrdfuse** [comment]
no no you were right in your remarks, those were sloppy merges

**Pull request merged**
